print("This function is called indexing and slicing.")
tupple=(0,1,2,3,4,5,6)
print("It will print from start to end")
print(tupple[:])
print("This will print from index 0 to end")
print(tupple[0:])
print("This will print from start index to n-1 index")
print(tupple[:4])
print("This will print from index 2 to 6-1=5 index")
print(tupple[2:6])